import math1 from './numbers1';
import multi2, { pow2, sum2, sub2 } from './numbers2';
import math3 from './numbers3';
export const pow = pow2;
export const sum = sum2;
export const sub = sub2;
export const sqrt = math3;
export const multi = multi2;
const cube = math1;
export default cube;